# Generated by Django 2.2 on 2019-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190404_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='more',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
