# Generated by Django 2.2 on 2019-04-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190407_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
